[package]
name = "frittata"
version = "0.1.0"
description = "gpg pinentry helper"
authors = ["octavore"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "frittata_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
async-trait = "0.1"
base64 = "0.22.1"
block2 = "0.6.2"
log = "0.4.28"
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-core-foundation = "0.3.2"
objc2-foundation = "0.3.2"
objc2-local-authentication = "0.3.2"
objc2-security = "0.3.2"
percent-encoding = "2.3.2"
regex = "1.12.2"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "3.15.1", features = ["base64"] }
tauri = { version = "2", features = [] }
tauri-plugin-cli = "2"
tauri-plugin-log = "2"
tauri-plugin-opener = "2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
uuid = { version = "1.18.1", features = ["serde", "v4"] }

